name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: npm install, build, and test
      run: |
        echo "hello world!"
      env:
        CI: true
