name: debug

on:
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GITHUB
      env:
        GH: ${{toJson(github)}}
      run: |
        echo ${GH}
    - name: JB
      env:
        JB: ${{toJson(job)}}
      run: echo ${JB}
