name: debug

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GITHUB
      env:
        GH: ${{toJson(github)}}
      run: |
        echo ${GH}
    - name: JB
      env:
        JB: ${{toJson(job)}}
      run: echo ${JB}
    - name: fail shell
      run: grep "hello" ./no_file.txt
    - name: backup plan
      if: failure()
      run: echo "everything is OK"
